vegetables = ["tomatoes", "potatoes", "onions"]
print(vegetables)
vegetables.remove("onions")
print(vegetables)
vegetables.append("carrots") 
print(vegetables)
vegetables.append("cucumbers")
print(vegetables)
vegetables.sort()
print("Updated Vegetable Inventory:",vegetables)
